apiVersion: apps/v1
kind: Deployment
metadata:
  name: seratos-api
  namespace: seratos
  labels:
    apiserver: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      apiserver: 'true'
  template:
    metadata:
      labels:
        apiserver: 'true'
    spec:
      serviceAccountName: apiserver
      containers:
      - name: etcd
        image: quay.io/coreos/etcd:v3.2.24
      - name: seratos-api
        image: marcos30004347/seratos-api:latest
        imagePullPolicy: Never
        args:
        - --etcd-servers=http://localhost:2379
        - --cert-dir=/tmp/certs
        - --secure-port=8443
        - --v=4
