kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aggregated-apiserver-clusterrole
rules:
- apiGroups: ['']
  resources: ['namespaces']
  verbs: ['get', 'watch', 'list']
- apiGroups: ['admissionregistration.k8s.io']
  resources: ['mutatingwebhookconfigurations', 'validatingwebhookconfigurations']
  verbs: ['get', 'watch', 'list']

- apiGroups:
  - apps
  resources:
  - deployments
  - pods
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups:
  - apps
  resources:
  - deployments/status
  - pods/status
  verbs: ["get", "update", "patch"]
- apiGroups:
  - seratos.microservice
  resources:
  - ats
  - microservices
  - events
  - eventhandlers
  - eventbindings
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups:
  - seratos.microservice
  resources:
  - ats/status
  - microservices/status
  - events/status
  - eventhandlers/status
  - eventbindings/status
  verbs: ["get", "list", "update", "patch"]

- apiGroups:
  - flowcontrol.apiserver.k8s.io
  resources:
  - flowschemas
  - prioritylevelconfigurations
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups:
  - ""
  resources:
  - secrets
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups:
  - ""
  resources:
  - services
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
