apiVersion: seratos.microservice/v1beta1
kind: Microservice
metadata:
  name: serviceA
spec:
  container: marcos30004347/consul-sidecar:latest
  env:
    - name: PORT
      value: 8080
    - name: TESTE
      value: "hahahah"
  topology:
    proxys:
      - service: serviceB
        ports:
          tcp: 80
          http2: 81
      - host: 127.0.0.1:2932
        ports:
          tcp: 82
    security:
      policy: blocks
      blocks:
          - serviceC
          - serviceD
          - serviceE
      allow:
          - serviceF
          - serviceG
          - serviceH
