apiVersion: seratos.microservice/v1
kind: Microservice
metadata:
  name: serviceA
  namespace: clusterA
spec:
  container: marcos30004347/consul-sidecar:latest
  env:
    PORT: 8080
  topology:
    proxy:
      - microservice:
        name: serviceB
        ports:
          tcp: 80
          http2: 81
      - server:
        host: 127.0.0.1:2932
        ports:
          tcp: 82
          http2: 83
    security:
      policy: blocks
      blocks:
          - serviceC
          - serviceD
          - serviceE
      allow:
          - serviceF
          - serviceG
          - serviceH
