apiVersion: seratos.microservice/v1
kind: Microservice
metadata:
  name: serviceA
  namespace: clusterA
spec:
  container: marcos30004347/consul-sidecar:latest
  env:
    - PORT: 8080
  topology:
    proxys:
      - service: serviceB
        ports:
          tcp: 80
          http2: 81
      - host: 127.0.0.1:2932
        ports:
          tcp: 82
    security:
      policy: blocks
      blocks:
          - serviceC
          - serviceD
          - serviceE
      allow:
          - service: serviceF
          - serviceG
          - serviceH
