---
apiVersion: seratos.microservice/v1beta1
kind: ProxySidecar
metadata:
  name: topology-config
spec:
  sidecars: 
  - name: envoy
    env:
      - name: TESTE
        value: '{{ proxy.spec.forward }}'
    event:
      created:
          - name: create-consul-intention
            exec: consul intention serviceA serviceB
      updated:
        container:
          - name: test-job
            env:
              name: TESTE
              value: "AHAHAHHA"


---
apiVersion: seratos.microservice/v1
kind: Sidecar
metadata:
  name: envoy
spec:
  container: marcos30004347/envoy:latest
  env:
    - TESTE: Teste

---
apiVersion: seratos.microservice/v1
kind: EventHandler
metadata:
  name: onSidecarCreationHandler
spec:
  subjectKind: Microservice
  command:
    exec: echo "{{ microservice.spec.container }}"
  selector:
    matchLabels:
      name: consul-client

---
apiVersion: seratos.microservice/v1
kind: EventBinding
metadata:
spec:
  on:
    - created
  handler: onSidecarCreationHandler
  subjects:
    - kind: Microservice
      selector:
        matchLabels:
          group: consul-mesh

---
apiVersion: seratos.microservice/v1
kind: Event
metadata:
  name: Microservice::serviceA(created)
  labels:
    event: created
spec:
  kind: Microservice
  name: serviceA
  event: created 
